import { pipeline } from '@xenova/transformers';

// import express from "express";
// const app = express();

// const port = 3000;


// app.get("/", (req, res) => {
//     res.send("Started Working, Express!");
// });

// app.listen(port, () => {
//     console.log(`Server listening at port: ${port}`);
// });



async function lol() {
 
    const summarization = await pipeline('summarization', 'Xenova/flan-t5-small');
    const input = 'The tiger (Panthera tigris) is the largest living cat species and a member of the genus Panthera. It is most recognisable for its black stripes on orange fur with a white underside. An apex predator, it primarily preys on ungulates, such as deer and wild boar. It is territorial and generally a solitary but social predator, requiring large contiguous areas of habitat to support its requirements for prey and rearing of its offspring. Tiger cubs stay with their mother for about two years and then become independent, leaving their mothers home range to establish their own.' +
    'The tiger was first scientifically described in 1758. It once ranged widely from the Eastern Anatolia Region in the west to the Amur River basin in the east, and in the south from the foothills of the Himalayas to Bali in the Sunda Islands. Since the early 20th century, tiger populations have lost at least 93% of their historic range and have been extirpated from Western and Central Asia, the islands of Java and Bali, and in large areas of Southeast and South Asia and China. What remains of the range where tigers still roam free is fragmented, stretching in spots from Siberian temperate forests to subtropical and tropical forests on the Indian subcontinent, Indochina and a single Indonesian island, Sumatra.' +
    'The tiger is listed as Endangered on the IUCN Red List. India hosts the largest tiger population. Major reasons for population decline are habitat destruction, habitat fragmentation and poaching. Tigers are also victims of human–wildlife conflict, due to encroachment in countries with a high human population density.' +
    'The tiger is among the most recognisable and popular of the worlds charismatic megafauna. It featured prominently in the ancient mythology and folklore of cultures throughout its historic range and continues to be depicted in modern films and literature, appearing on many flags, coats of arms and as mascots for sporting teams. The tiger is the national animal of India, Bangladesh, Malaysia and South Korea.' +
    'EtymologyThe Old English tigras derive from Old French tigre, from Latin tigris. This was a borrowing of Classical Greek τίγρις tigris.[4][5] The ultimate origin of the word is uncertain.[6] Ancient Greek geographer Strabo suggested an Armenian origin.[7] One popular idea, believed in the 16th and 17th centuries, is tiger was a transliteration of the Middle Persian tigr, meaning arrow, from which the name of the river Tigris may also have been derived. Thus, the animal and the river may have both been associated with speed. The connection between the two words is doubted in modern times, and they are likely to be Latin homonyms.[6]' +
    'TaxonomyIn 1758, Carl Linnaeus described the tiger in his work Systema Naturae and gave it the scientific name Felis tigris.[2] In 1929, the British taxonomist Reginald Innes Pocock subordinated the species under the genus Panthera using the scientific name Panthera tigris.[8][9]' +
    'SubspeciesFollowing Linnaeuss first descriptions of the species, several tiger zoological specimens were described and proposed as subspecies.[10] The validity of several tiger subspecies was questioned in 1999. Most putative subspecies described in the 19th and 20th centuries were distinguished on the basis of fur length and colouration, striping patterns and body size, hence characteristics that vary widely within populations. Morphologically, tigers from different regions vary little, and gene flow between populations in those regions is considered to have been possible during the Pleistocene. Therefore, it was proposed to recognize only two tiger subspecies as valid, namely P. t. tigris in mainland Asia, and P. t. sondaica in the Greater Sunda Islands. Mainland tigers are described as being larger in size with generally lighter fur and fewer stripes, while island tigers are smaller due to insular dwarfism, with darker coats and more numerous stripes.[11] The stripes of island tigers may break up into spotted patterns.[12]' +
    'This two-subspecies proposal was reaffirmed in 2015 by a comprehensive analysis of morphological, ecological and molecular traits of all putative tiger subspecies using a combined approach. The authors proposed recognition of only two subspecies, namely P. t. tigris comprising the Bengal, Malayan, Indochinese, South Chinese, Siberian and Caspian tiger populations of continental Asia, and P. t. sondaica comprising the Javan, Bali and Sumatran tiger populations of the Sunda Islands. The continental nominate subspecies P. t. tigris constitutes two clades: a northern clade composed of the Siberian and Caspian tiger populations, and a southern clade composed of all other mainland populations. The authors noted that this two-subspecies reclassification will impact tiger conservation management.[13] It would make captive breeding programs and future re-wilding of zoo-born tigers easier, as one tiger population could then be used to reinforce another. However, there is the risk that the loss of subspecies uniqueness could lead to less protection efforts for specific populations.[14]' +
    'In 2017, the Cat Classification Task Force of the IUCN Cat Specialist Group revised felid taxonomy in accordance with the two-subspecies proposal of the comprehensive 2015 study, and recognized the tiger populations in continental Asia as P. t. tigris, and those in the Sunda Islands as P. t. sondaica.[15] This two-subspecies view is still disputed by researchers, since the currently recognized six living subspecies can be distinguished genetically.[14] Results of a 2018 whole-genome sequencing of 32 samples support six monophyletic tiger clades corresponding with the six living proposed subspecies and indicate they descended from a common ancestor around 110,000 years ago.[16] Studies in 2021 and 2023 also affirmed the genetic distinctiveness and separation of these tigers.[17][18]' +
    'The following tables are based on the classification of the species Panthera tigris provided in Mammal Species of the World,[10] and also reflect the classification used by the Cat Classification Task Force in 2017:[15]' +
    'Behaviour and ecology' +
    'Social spacing' +
    'Adult tigers lead largely solitary lives. They establish and maintain home ranges, the size of which mainly depends on prey abundance, geographic area and sex of the individual. Males and females defend their home ranges from those of the same sex, and the home range of a male encompasses that of multiple females.[12][55] Two females in the Sundarbans had home ranges of 10.6 and 14.1 km2 (4.1 and 5.4 sq mi).[77] In Panna Tiger Reserve, the home ranges of five reintroduced females varied from 53–67 km2 (20–26 sq mi) in winter to 55–60 km2 (21–23 sq mi) in summer and to 46–94 km2 (18–36 sq mi) during monsoon; three males had 84–147 km2 (32–57 sq mi) large home ranges in winter, 82–98 km2 (32–38 sq mi) in summer and 81–118 km2 (31–46 sq mi) during monsoon seasons.[78] In Huai Kha Khaeng Wildlife Sanctuary, seven resident females had home ranges of 44.1–122.3 km2 (17.0–47.2 sq mi) and four resident males of 174.8–417.5 km2 (67.5–161.2 sq mi).[79] Four male problem tigers in Sumatra were translocated to national parks and needed 6–17 weeks to establish new home ranges of 37.5–188.1 km2 (14.5–72.6 sq mi).[80] Ten solitary females in Sikhote-Alin Biosphere Reserve had home ranges of 413.5 ± 77.6 km2 (159.7 ± 30.0 sq mi); when they had cubs of up to 4 months of age, their home ranges declined to 177.3 ± 53.5 km2 (68.5 ± 20.7 sq mi) and steadily grew to 403.3 ± 105.1 km2 (155.7 ± 40.6 sq mi) until the cubs were 13–18 months old.[81]' +
    'The tiger is a long-ranging species, and individuals disperse over distances of up to 650 km (400 mi) to reach tiger populations in other areas.[82] Young tigresses establish their first territories close to their mothers. Males, however, migrate further than their female counterparts and set out at a younger age to mark out their own area.[83] Four radio-collared females in Chitwan dispersed between 0 and 43.2 km (0.0 and 26.8 mi), and 10 males between 9.5 and 65.7 km (5.9 and 40.8 mi).[84] A young male may have to live as a transient in another males territory until he is older and strong enough to challenge the resident male. Young males thus have an annual mortality rate of up to 35%. By contrast, young female tigers die at a rate of only around 5%.[83] Tigers mark their territories by spraying urine on vegetation and rocks, clawing or scent rubbing trees, and marking trails with feces, anal gland secretions and ground scrapings.[55][85][86][87] Scent markings also allow an individual to pick up information on anothers identity. A tigress in oestrus will signal her availability by scent marking more frequently and increasing her vocalisations. Unclaimed territories, particularly those that belonged to a decreased individual, can be taken over in days or weeks.[55]' +
    'Male tigers are generally less tolerant of other males within their territories than females are of other females. Territory disputes are usually solved by intimidation rather than outright violence. Once dominance has been established, a male may tolerate a subordinate within his range, as long as they do not live in too close quarters. The most serious disputes tend to occur between two males competing for a female in oestrus.[88] Though tigers mostly live alone, relationships between individuals can be complex. Tigers are particularly social at kills, and a male tiger will share a carcass with the females and cubs within this territory and unlike male lions, will allow them to feed on the kill before he is finished with it. Though the female and male act amicably, females are more tense towards each other at a kill.[89][90]' +
    'Communication' +
    'Tiger baring teeth as a sign of aggression' +
    'Captive tiger roaring' +
    'During friendly encounters and bonding, tigers rub against each others bodies.[91] Facial expressions include the "defense threat", which involves a wrinkled face, bared teeth, pulled-back ears, and widened pupils.[91][12] Both males and females show a flehmen response, a characteristic grimace, when sniffing urine markings. Males also use the flehman to detect the markings made by tigresses in oestrus.[12] Tigers also use their tails to signal their mood. To show cordiality, the tail sticks up and sways slowly, while an apprehensive tiger lowers its tail or wags it side-to-side. When calm, the tail hangs low.[92]' +
    'Tigers are normally silent but can produce numerous vocalisations.[93][94] They roar to signal their presence to other individuals over long distances. This vocalisation is forced through an open mouth as it closes and can be heard 3 km (1.9 mi) away. A tiger may roar three or four times in a row, and others may respond in kind. Tigers also roar during mating, and a mother will roar to call her cubs to her. When tense, tigers will moan, a sound similar to a roar but softer and made when the mouth is at least partially closed. Moaning can be heard 400 m (1,300 ft) away.[12][95]' +
    'Aggressive encounters involve growling, snarling and hissing.[96] An explosive "coughing roar" or "coughing snarl" is emitted through an open mouth and exposed teeth.[12][96][97] Chuffing—soft, low-frequency snorting similar to purring in smaller cats—is heard in more friendly situations.[98] Mother tigers communicate with their cubs by grunting, while cubs call back with miaows.[99] A "woof" sound is produced when the animal is startled. It has also been recording emitting a deer-like "pok" sound for unknown reasons, but most often at kills.[100][101]' +
    'Hunting and diet' + 
    'Tiger attacking a sambar deer in Ranthambore Tiger Reserve' +
    'The tiger is a carnivore and an apex predator feeding mainly on ungulates, with a particular preference for sambar deer, Manchurian wapiti, barasingha and wild boar. Tigers kill large prey like gaur,[102] but opportunistically kill much smaller prey like monkeys, peafowl and other ground-based birds, porcupines and fish.[12][55] Tiger attacks on adult Asian elephants and Indian rhinoceros have also been reported.[103][104][105] More often, tigers take the more vulnerable small calves.[106] When in close proximity to humans, tigers sometimes prey on domestic livestock and dogs.[12] Tigers occasionally consume vegetation, fruit and minerals for dietary fibre.[107]' +
    'Tigers learn to hunt from their mothers, which is important but not necessary for their success.[108] They usually hunt alone, but families hunt together when cubs are old enough.[109] A tiger travels up to 19.3 km (12.0 mi) per day in search of prey, using vision and hearing to find a target.[110] It also waits at a watering hole for prey to come by, particularly during hot summer days.[111][112] It is an ambush predator and when approaching potential prey, the tiger crouches, with head lowered, and hides in foliage. It switches between creeping forward and staying still. Tigers have been recorded dozing off while in still mode, and can stay in the same spot for as long as a day waiting for prey and launches an attack, when the prey is close enough,[113] usually within 30 m (98 ft).[49] If the prey spots it before then, the cat does not pursue further.[111] Tigers can sprint 56 km/h (35 mph) and leap 10 m (33 ft);[114][115] they are not long distance runners and give up a chase if prey outpaces them over a certain distance.[111]' +
    'Two tigers working together to kill an Indian boar in Kanha Tiger Reserve' +
    'The tiger attacks from behind or at the sides and tries to knock the target off balance. It latches onto prey with its forelimbs, twisting and turning during the struggle. The tiger generally applies a bite to the throat until its target dies of strangulation.[12][116][117] Holding onto the throat puts the cat out of reach of the horns, antlers, tusks and hooves.[116][118] Tigers are adaptable killers and may use other methods, including ripping the throat or breaking the neck. Large prey may be disabled by a bite to the back of the hock, severing the tendon. Swipes from the large paws are capable of stunning or breaking to skull of a water buffalo.[119] They kill small prey with a bite to the back of the neck or skull.[120][49] Estimates of the success rate for hunting tigers ranges from a low 5% to a high of 50%. They are sometimes killed or injured by large or dangerous prey like gaur, buffalo and gaur.[49]' +
    'The tiger typically drags its kill for 183–549 m (600–1,801 ft) to a hidden, usually vegetated spot before eating. The tiger has the strength to drag the carcass of a fully grown buffalo for some distance, a feat three men struggle with. It rests for a while before eating and can consume as much as 50 kg (110 lb) of meat in one session, but feeds on a carcass for several days, leaving very little for scavengers.[121]' +
    'Enemies and competitors' +
    'Tigers may kill and even prey on other predators they coexist with.[122] In much of their range, tigers share habitat with leopards and dholes. They typically dominate both of them, though large packs of dholes can drive away a tiger,[123] or even kill it.[124] Tigers appear to inhabit the deep parts of a forest while these smaller predators are pushed closer to the fringes.[125] The three predators coexist by hunting different prey.[126] In one study, tigers were found to have killed prey that weighed an average of 91.5 kg (202 lb), in contrast to 37.6 kg (83 lb) for the leopard and 43.4 kg (96 lb) for the dhole.[127] Leopards can live successfully in tiger habitat when there is abundant food and vegetation cover, and there is no evidence of competitive exclusion.[126] Nevertheless, leopards avoid areas were tigers roam and are less common where tigers are numerous.[122][128][129]' +
    'Tigers tend to be wary of sloth bears, with their sharp claws, quickness and ability to stand on two legs. Tiger do sometimes prey on sloth bears by ambushing them when they are feeding at termite mounds.[130] Siberian tigers may attack, kill and prey on Ussuri brown and Ussuri black bears.[12] In turn, some studies show that brown bears frequently track down tigers to usurp their kills, with occasional fatal outcomes for the tiger.[131][132][133]' +
    'Reproduction and life cycle' +
    'The tiger mates all year round, but most cubs are born between March and June, with another peak in September.[134] A tigress is in oestrus for three to six days, inbetween three to nine week intervals.[12] A resident male mates with all the females within his territory, who signal their receptiveness by roaring and marking.[135][136] Younger, transient males are also attracted, leading to a fight in which the more dominant male drives the usurper off.[134][135] During courtship, the male is cautious with the female as he waits for her to show signs she is ready to mate. She signals to him by positioning herself in lordosis with their tail to the side. Copulation is generally 20 to 25 seconds long, with the male biting the female by the scruff of her neck. After it is finished, the male quickly pulls away as the female may turn and slap him.[135] Tiger pairs may stay together for up to four days and mate multiple times.[137] Gestation ranges from 93 to 114 days, with an average of 103 to 105 days.[134]' +
    'A tigress gives birth in a secluded location, be it in dense vegetation, in a cave or under a rocky shelter.[138] Litters consist of as many as seven cubs, but two or three are more typical.[134][138] Newborn cubs weigh 785–1,610 g (27.7–56.8 oz), and are blind and altricial.[138] The mother licks and cleans her cubs, suckles them and viscously defends them from any potential threat.[134] She will only leave them alone to hunt, and even then does not travel far.[139] When a mother suspects an area is no longer safe, she moves her cubs to a new spot, transporting them one by one by grabbing them by the scruff of the neck with her mouth. The mortality rate for tiger cubs can reach 50% during these early months, causes of death include predators like dholes, leopards and pythons.[140] Young are able to see in a week, can leave the denning site in two months and around the same time they start eating meat.[134][141]' +
    'After around two months, the cubs are able to follow their mother. They still hide in vegetation when she goes hunting, and she will guide them to the kill. Cubs bond though play fighting and practice stalking. A hierarchy develops in the litter, with the biggest cub, often a male, being the most dominant and the first to eat its fill at a kill.[142] Around the age of six months, cubs are fully weaned and have more freedom to explore their environment. Between eight and ten months, they accompany their mother on hunts.[140] A cub can make a kill as early as 11 months, and reach independence around 18 to 24 months of age, males becoming independent earlier than females.[143] Radio-collared tigers in Chitwan started dispersing from their natal areas earliest at the age of 19 months.[84] Young females are sexual mature at three to four years, whereas males are at four to five years. Tigers may live up to 26 years.[12]' +
    'Tiger fathers play no role in raising the young, but he may encounter and interact with them. The resident male appears to visit the female-cub families within his territory. They may socalise and even share kills with them.[144][145] One male was recorded looking after cubs whose mother had died.[146] By defending his territory, the male is also protecting the females and cubs from other males.[147] When a new male takes over a territory, dependent cubs are at risk of being killed, as the male would want to sire his own young with the females. Older female cubs are tolerated but males may be treated as potential competitors.[148]';

    const result = await summarization(input, {
        min_length: 200, max_length: 1000,
    });

    console.log("\n" + "\n" + "\n" + "\n" + "\n" + result[0].summary_text + "\n" + "\n" + "\n" + "\n" + "\n");

}